spring:
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:8080/local/introspect
          client-id: test-client
          client-secret: secret

logging:
  level:
    org.springframework.security: DEBUG
