GET http://localhost:8080/api/hello
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOlsiaGVsbG8tc2VydmljZSJdLCJzdWIiOiJqZG9lIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInNjb3BlIjoib3BlbmlkIGVtYWlsIHByb2ZpbGUiLCJpc3MiOiJ0ZXN0X2lzc3VlciIsIm5hbWUiOiJKb2huIERvZSIsImdyb3VwcyI6WyJ1c2VyIl0sInByZWZlcnJlZF91c2VybmFtZSI6IkpvaG4gRG9lIiwiZXhwIjoxNzA5ODAwMTMwLCJnaXZlbl9uYW1lIjoiSm9obiIsImZhbWlseV9uYW1lIjoiRG9lIiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSJ9.SmAA3nSw7pwBijhcmPBA98qyekSNpfPulSJ_RNUZWz8
